### ISSUE TITLE
Find Restaurant

### ISSUE THREAD

**Issue by waltergalvao** [waltergalvao/dishlist.mobile#3]
(Also known as Search screen)

Users must see a search bar to search the restaurant by name/part of the name. After click "Search", Users must see a list of results below the bar. After selecting a restaurant, user is directed to Menu screen to see the restaurant's menu.

- [x] Create Search page with a search bar

- [x] Focus should already be on search bar with open keyboard

- [x] Create search functionality

- [x] Create a list of results. When users select one of the results, redirect to Menu screen (choosen option refers to the restaurant's ID)

- [x] Styling

- [x] Add 500ms bouncing

- [x] Add loading progress indicator

- [x] Add message "No restaurants found" if search has no result.

**Comment by wbgneto** [comment]
Added tasks

**Comment by heloysatancredo** [comment]
Nov 17 Tests - corrections to be done:
- Search box border-radius (it just has border-radius when on focus; otherwise no)
- Cache: even when restarting the search (erasing search box), the header keeps last searched restaurant name. I believe this header should ALWAYS display "Search by name" (as in the mockups)
- Necessary to confirm if updating the list from the 1st letter is a good practice (because of excessive calls on the server)
- Add a message "No restaurants found" if the search has no result.
